<!-- JS here -->
<script src="{{ asset('frontend/assets/js/jquery.js') }}"></script>
<script src="{{ asset('frontend/assets/js/waypoints.js') }}"></script>
<script src="{{ asset('frontend/assets/js/modernizr.js') }}"></script>
<script src="{{ asset('frontend/assets/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('frontend/assets/js/meanmenu.js') }}"></script>
<script src="{{ asset('frontend/assets/js/swiper-bundle.js') }}"></script>
<script src="{{ asset('frontend/assets/js/slick.js') }}"></script>
<script src="{{ asset('frontend/assets/js/magnific-popup.js') }}"></script>
<script src="{{ asset('frontend/assets/js/counterup.js') }}"></script>
<script src="{{ asset('frontend/assets/js/wow.js') }}"></script>
<script src="{{ asset('frontend/assets/js/nice-select.js') }}"></script>

<script src="{{ asset('frontend/assets/js/tilt.jquery.min.js') }}"></script>
<script src="{{ asset('frontend/assets/js/isotope-pkgd.js') }}"></script>
<script src="{{ asset('frontend/assets/js/imagesloaded-pkgd.js') }}"></script>
<script src="{{ asset('frontend/assets/js/ajax-form.js') }}"></script>
<script src="{{ asset('frontend/assets/js/headline.js') }}"></script>
<script src="{{ asset('frontend/assets/js/main.js') }}"></script>
