CREATE TABLE contacts (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NULL,
email VARCHAR(255) NULL,
phone VARCHAR(255) NULL,
topic VARCHAR(255) NULL,
description LONGTEXT NULL,
status TINYINT(4) NOT NULL DEFAULT 1 COMMENT '1 is active 0 is inactive',
created_at DATETIME  NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
