CREATE TABLE sub_menus (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
menu_id INT(11) NOT NULL,
name VARCHAR(255) NOT NULL,
route VARCHAR(255) NOT NULL,
status TINYINT(4) NOT NULL DEFAULT 1 COMMENT '1 is active 0 is inactive',
created_at DATETIME  NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
